### ISSUE TITLE
Running "smt repeat x" using Python 2.7 leads to deepcopy issue

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#100]
I just used sumatra for the first time to create a run of my model. 
The goal is to create a run that I can repeat as I work on the model, 
and check if the output remains constant. However, when I issued: 

{{{
$ smt repeat primary_test 
Traceback (most recent call last): 
  File "/usr/people/hiemstra/progsandlibs/bin/smt", line 5, in 
<module> 
    pkg_resources.run_script('Sumatra==0.3.1.dev', 'smt') 
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 467, 
in run_script 
    self.require(requires)[0].run_script(script_name, ns) 
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1200, 
in run_script 
    execfile(script_filename, namespace, namespace) 
  File "/usr/people/hiemstra/progsandlibs/lib/python2.7/site-packages/ 
Sumatra-0.3.1.dev-py2.7.egg/EGG-INFO/scripts/smt", line 33, in 
<module> 
    main(sys.argv[2:]) 
  File "/usr/people/hiemstra/progsandlibs/lib/python2.7/site-packages/ 
Sumatra-0.3.1.dev-py2.7.egg/sumatra/commands.py", line 441, in repeat 
    original = deepcopy(tmp) 
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy 
    y = _reconstruct(x, rv, 1, memo) 
  File "/usr/lib/python2.7/copy.py", line 344, in _reconstruct 
    state = deepcopy(state, memo) 
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy 
    y = copier(x, memo) 
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict 
    y[deepcopy(key, memo)] = deepcopy(value, memo) 
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy 
    y = copier(x, memo) 
  File "/usr/lib/python2.7/copy.py", line 298, in _deepcopy_inst 
    state = deepcopy(state, memo) 
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy 
    y = copier(x, memo) 
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict 
    y[deepcopy(key, memo)] = deepcopy(value, memo) 
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy 
    y = copier(memo) 
TypeError: cannot deepcopy this pattern object 
}}}

After googling a bit, I found this issue: http://bugs.python.org/issue10076 
: on the bugtracker of python. I think the problem is that the Project 
class does not provide a __deepcopy__ function. I also tried to 
replace deepcopy by copy in commands.py:line 441 (I thought, just give 
it a try :)), but this led to the following error: 

{{{
$ smt repeat primary_test 
Traceback (most recent call last): 
  File "/usr/people/hiemstra/progsandlibs/bin/smt", line 5, in 
<module> 
    pkg_resources.run_script('Sumatra==0.3.1.dev', 'smt') 
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 467, 
in run_script 
    self.require(requires)[0].run_script(script_name, ns) 
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1200, 
in run_script 
    execfile(script_filename, namespace, namespace) 
  File "/usr/people/hiemstra/progsandlibs/lib/python2.7/site-packages/ 
Sumatra-0.3.1.dev-py2.7.egg/EGG-INFO/scripts/smt", line 33, in 
<module> 
    main(sys.argv[2:]) 
  File "/usr/people/hiemstra/progsandlibs/lib/python2.7/site-packages/ 
Sumatra-0.3.1.dev-py2.7.egg/sumatra/commands.py", line 444, in repeat 
    original.repository.checkout() # should do nothing if there is 
already a checkout 
  File "/usr/people/hiemstra/progsandlibs/lib/python2.7/site-packages/ 
Sumatra-0.3.1.dev-py2.7.egg/sumatra/versioncontrol/_mercurial.py", 
line 129, in checkout 
    local_repos = hg.repository(self._ui, path, create=True) 
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 94, in 
repository 
    repo = _lookup(path).instance(ui, path, create) 
  File "/usr/lib/python2.7/site-packages/mercurial/localrepo.py", line 
2049, in instance 
    return localrepository(ui, util.drop_scheme('file', path), create) 
  File "/usr/lib/python2.7/site-packages/mercurial/localrepo.py", line 
68, in __init__ 
    raise error.RepoError(_("repository %s already exists") % path) 
mercurial.error.RepoError: repository /nobackup/users/hiemstra/speedo/ 
speedo_blackbox_tests already exists 
}}}

Some information on my system: 

{{{
$ uname -a 
Linux bhp012.host.nl 2.6.35.13-92.fc14.i686.PAE #1 SMP Sat May 21 
17:33:09 UTC 2011 i686 i686 i386 GNU/Linux 
$ python --version 
Python 2.7 
$ smt 
Usage: smt <subcommand> [options] [args] 
Simulation/analysis management tool version 0.3.1.dev 
}}}
        

 _Imported from Bitbucket issue [93](https://bitbucket.org/apdavison/sumatra/issue/93),  created by apdavison on 03-29-2012 at 07:43, last modified: 05-02-2012 at 10:59_

**Comment by apdavison** [comment]
This turns out to be a problem with deepcopy of `ConfigParserParameterSet` objects, which I had not seen before since I mostly use `SimpleParameterSet` or `NTParameterSet`  in the tests and in my own code.

The problem should be fixed in r298
        

_Trac comment by apdavison on 04-19-2012 at 14:08_

**Comment by apdavison** [comment]
This fixed the problem! Thanks...
        

_Trac comment by anonymous on 05-02-2012 at 10:59_
