### ISSUE TITLE
NULL value for executable version crashes Django ORM record store

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#141]
My MATLAB version was never parsed correctly, so the version value kept being NULL. This was a problem for the Django ORM record store. Here's a traceback I get after doing a 'smt run':
{{{
No data produced.
Created record store
Traceback (most recent call last):
  File "/users/slic/timlin/local/bin/smt", line 5, in <module>
    pkg_resources.run_script('Sumatra==0.5.0', 'smt')
  File "/users/slic/timlin/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/EGG-INFO/scripts/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/commands.py", line 328, in run
    launch_mode=launch_mode)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/projects.py", line 176, in launch
    self.add_record(record)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/projects.py", line 202, in add_record
    self.record_store.save(self.name, record)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/recordstore/django_store/__init__.py", line 178, in save
    db_record.executable = self._get_db_obj('Executable', record.executable)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/recordstore/django_store/__init__.py", line 163, in _get_db_obj
    db_obj, created = cls.objects.get_or_create_from_sumatra_object(obj, using=self._db_label)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Sumatra-0.5.0-py2.7.egg/sumatra/recordstore/django_store/models.py", line 36, in get_or_create_from_sumatra_object
    return self.using(using).get_or_create(**attributes)            
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/query.py", line 452, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/users/slic/timlin/local/lib/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: django_store_executable.version may not be NULL
}}}

        

 _Imported from Bitbucket issue [137](https://bitbucket.org/apdavison/sumatra/issue/137),  created by apdavison on 02-27-2013 at 01:33, last modified: 04-03-2013 at 10:11_

**Comment by apdavison** [comment]
Dependency.version is supposed to be 'unknown' if the version cannot be found. It is therefore a bug that "None" got anywhere near the ORM.
        

_Trac comment by apdavison on 04-03-2013 at 09:34_

**Comment by apdavison** [comment]
Just realized this bug concerns Executable.version. In any case, this also should never be None.
        

_Trac comment by apdavison on 04-03-2013 at 10:05_

**Comment by apdavison** [comment]
fixed in r692
        

_Trac comment by apdavison on 04-03-2013 at 10:11_
