### ISSUE TITLE
Record store fails on Windows for non-ASCII username (django.db.utils.DatabaseError)

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#172]
I'm trying to use Sumatra v0.5.2 on Windows 7 x64 with Python 2.7.2 (32 bit), Django v1.4.2 and Mercurial v2.1.1.
When I run my script the output suggests that everything is working fine, but when saving Django raises an exception:

```
Y:\Experimente\smt-multiprocess-temp>smt run --main=simple.py
Using C:\Python27\python.exe
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
INFO:__main__:Starting random data generation
DEBUG:__main__:Save to Data/statistics.npy...
Computation took 0.757 s
Data keys are [statistics.npy(5eeaa836c2d4ef20de0db97c490f9c155400f65d)]
Traceback (most recent call last):
  File "C:\Python27\Scripts\smt", line 5, in <module>
    pkg_resources.run_script('sumatra==0.5.2', 'smt')
  File "C:\Python27\lib\site-packages\distribute-0.6.28-py2.7.egg\pkg_resources.py", line 499, in ru
n_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\distribute-0.6.28-py2.7.egg\pkg_resources.py", line 1239, in r
un_script
    execfile(script_filename, namespace, namespace)
  File "c:\python27\lib\site-packages\sumatra-0.5.2-py2.7.egg\EGG-INFO\scripts\smt", line 31, in <mo
dule>
    main(sys.argv[2:])
  File "C:\Python27\lib\site-packages\sumatra-0.5.2-py2.7.egg\sumatra\commands.py", line 328, in run

    launch_mode=launch_mode)
  File "C:\Python27\lib\site-packages\sumatra-0.5.2-py2.7.egg\sumatra\projects.py", line 176, in lau
nch
    self.add_record(record)
  File "C:\Python27\lib\site-packages\sumatra-0.5.2-py2.7.egg\sumatra\projects.py", line 202, in add
_record
    self.record_store.save(self.name, record)
  File "C:\Python27\lib\site-packages\sumatra-0.5.2-py2.7.egg\sumatra\recordstore\django_store\__ini
t__.py", line 189, in save
    db_record.save() # need to save before using many-to-many relationship
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: You must not use 8-bit bytestrings unless you use a text_factory that
 can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instea
d just switch your application to Unicode strings.
```

I logged the actual DB queries using these lines in ''sumatra\recordstore\django_store\models.py'':
```
#!python
# DEBUG
import logging
l = logging.getLogger('django.db.backends')
l.setLevel(logging.DEBUG)
l.addHandler(logging.FileHandler("django.log"))
```

The log indicates that there is a problem with a German umlaut ("ü") in my username, which I use for Mercurial (I deleted actual name and e-mail address, but left the problematic bit):
```
# The next line is the string "...müh..."

#################sm�h### <#####################@###############.de>

'##################m\xfch### <#####################@###############.##>'
```

Full log:
```
(0.015) SELECT "django_store_project"."id", "django_store_project"."name", "django_store_project"."description" FROM "django_store_project" WHERE "django_store_project"."id" = Windowstest ; args=(u'Windowstest',)
(0.000) SELECT "django_store_record"."label", "django_store_record"."db_id", "django_store_record"."reason", "django_store_record"."duration", "django_store_record"."executable_id", "django_store_record"."repository_id", "django_store_record"."main_file", "django_store_record"."version", "django_store_record"."parameters_id", "django_store_record"."launch_mode_id", "django_store_record"."datastore_id", "django_store_record"."input_datastore_id", "django_store_record"."outcome", "django_store_record"."timestamp", "django_store_record"."tags", "django_store_record"."diff", "django_store_record"."user", "django_store_record"."project_id", "django_store_record"."script_arguments", "django_store_record"."stdout_stderr" FROM "django_store_record" WHERE ("django_store_record"."project_id" = Windowstest  AND "django_store_record"."label" = 20130705-110006 ); args=(u'Windowstest', '20130705-110006')
(0.000) SELECT "django_store_executable"."id", "django_store_executable"."path", "django_store_executable"."name", "django_store_executable"."version", "django_store_executable"."options" FROM "django_store_executable" WHERE ("django_store_executable"."path" = C:\Python27\python.exe  AND "django_store_executable"."version" = 2.7.2  AND "django_store_executable"."name" = Python  AND "django_store_executable"."options" =  ); args=('C:\\Python27\\python.exe', '2.7.2', 'Python', '')
(0.000) SELECT "django_store_repository"."id", "django_store_repository"."type", "django_store_repository"."url", "django_store_repository"."upstream" FROM "django_store_repository" WHERE ("django_store_repository"."url" = Y:\Experimente\smt-multiprocess-temp  AND "django_store_repository"."type" = MercurialRepository  AND "django_store_repository"."upstream" = Y:\Experimente\smt-multiprocess ); args=(u'Y:\\Experimente\\smt-multiprocess-temp', 'MercurialRepository', u'Y:\\Experimente\\smt-multiprocess')
(0.000) SELECT "django_store_launchmode"."id", "django_store_launchmode"."type", "django_store_launchmode"."parameters" FROM "django_store_launchmode" WHERE ("django_store_launchmode"."type" = SerialLaunchMode  AND "django_store_launchmode"."parameters" = {'working_directory': 'Y:\\Experimente\\smt-multiprocess-temp'} ); args=('SerialLaunchMode', "{'working_directory': 'Y:\\\\Experimente\\\\smt-multiprocess-temp'}")
(0.000) SELECT "django_store_datastore"."id", "django_store_datastore"."type", "django_store_datastore"."parameters" FROM "django_store_datastore" WHERE ("django_store_datastore"."type" = FileSystemDataStore  AND "django_store_datastore"."parameters" = {'root': u'Data'} ); args=('FileSystemDataStore', "{'root': u'Data'}")
(0.000) SELECT "django_store_datastore"."id", "django_store_datastore"."type", "django_store_datastore"."parameters" FROM "django_store_datastore" WHERE ("django_store_datastore"."type" = FileSystemDataStore  AND "django_store_datastore"."parameters" = {'root': u'/'} ); args=('FileSystemDataStore', "{'root': u'/'}")
(0.000) SELECT "django_store_parameterset"."id", "django_store_parameterset"."type", "django_store_parameterset"."content" FROM "django_store_parameterset" WHERE ("django_store_parameterset"."content" = {}  AND "django_store_parameterset"."type" = dict ); args=('{}', 'dict')
(0.000) INSERT INTO "django_store_record" ("label", "reason", "duration", "executable_id", "repository_id", "main_file", "version", "parameters_id", "launch_mode_id", "datastore_id", "input_datastore_id", "outcome", "timestamp", "tags", "diff", "user", "project_id", "script_arguments", "stdout_stderr") VALUES (20130705-110006, , 5.42899990082, 2, 1, simple.py, 0e31d788b587, 1, 1, 1, 2, , 2013-07-05 11:00:06.817000, , , #################sm�h### <#####################@###############.de>, Windowstest, , INFO:__main__:Starting random data generation

DEBUG:__main__:Save to Data/statistics.npy...

Computation took 0.764 s

); args=['20130705-110006', '', 5.428999900817871, 2, 1, 'simple.py', '0e31d788b587', 1, 1, 1, 2, '', u'2013-07-05 11:00:06.817000', '', '', '##################m\xfch### <#####################@###############.##>', u'Windowstest', '', u'INFO:__main__:Starting random data generation\r\nDEBUG:__main__:Save to Data/statistics.npy...\r\nComputation took 0.764 s\r\n'
]
```

Probably the solution will be to use unicode strings internally and a safe encoding (e. g. UTF-8) when storing these strings.
        

 _Imported from Bitbucket issue [186](https://bitbucket.org/apdavison/sumatra/issue/186),  created by apdavison on 07-05-2013 at 09:18, last modified: 04-22-2014 at 07:51_

**Comment by apdavison** [comment]
Need to check whether this also occurs on Linux.
        

_Trac comment by apdavison on 08-27-2013 at 08:42_

**Comment by apdavison** [comment]
Hi,
I reported this issue in the old Trac system. I haven't worked with Sumatra in the meantime due to this issue, but I'm happy to help if you need to test possible fixes in new versions.
Keep up the good work and thank you for your efforts!
        

_Trac comment by joschkazj on 04-22-2014 at 07:34_

**Comment by apdavison** [comment]
Hi, thanks for the update.  I have recently bought a cheap Windows 7 machine specifically for testing, so I should be able to work on this soon.
        

_Trac comment by apdavison on 04-22-2014 at 07:51_

**Comment by apdavison** [comment]
This is probably fixed, unit test passes on Linux and OS X, but should test on Windows before declaring finally closed.

**Comment by joschkazj** [comment]
Thanks for the update, I will try it again and report back.
