### ISSUE TITLE
Directory within arguments leads to exception

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#174]
I was trying to start a simulation with sumatra where the last argument is a directory for storing the results, e.g.:
{{{
smt run -e python -m plume.py -- -c conf.py -o plume.h5 Data
}}}
However, this leads to an exception:
{{{
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin//smt", line 31, in <module>
    main(sys.argv[2:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sumatra/commands.py", line 297, in run
    parameters, input_data, script_args = parse_arguments(args, project.input_datastore)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sumatra/commands.py", line 77, in parse_arguments
    parameter_sets.append(build_parameters(arg))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sumatra/parameters.py", line 410, in build_parameters
    parameters = JSONParameterSet(filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sumatra/parameters.py", line 348, in __init__
    with open(initialiser) as fid:
IOError: [Errno 21] Is a directory: 'Data'
}}}
It seems sumatra is not checking whether an argument is an actual file and tries to treat them all as parameter files. Is there a workaround or solution for this problem?
        

 _Imported from Bitbucket issue [188](https://bitbucket.org/apdavison/sumatra/issue/188),  created by apdavison on 07-30-2013 at 06:41, last modified: 07-30-2013 at 06:42_

**Comment by apdavison** [comment]
Fixed in r774
        

_Trac comment by apdavison on 07-30-2013 at 06:42_
