### ISSUE TITLE
Tag most recent simulation fails after delete

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#176]
It seems that the pointer to the most recent simulation is not updated when the most recent simulation is deleted. At least trying to tag without specifying any label fails with a `KeyError`.

To reproduce:
 * Run two simulations. Say, the labels are `20131103-181000` and `20131103-181500`
 * Delete the latest simulation using `smt delete 20131103-181500`
 * Try to tag the most recent simulation `smt tag last_one`

The result should be a `KeyError`:
{{{
  Traceback (most recent call last):
    File "~/.pyenvs/sumatra/bin/smt", line 31, in <module>
      main(sys.argv[2:])
    File "~/.pyenvs/sumatra/lib/python2.7/site-packages/sumatra/commands.py", line 445, in tag
      labels = [project.most_recent().label]
    File "~/.pyenvs/sumatra/lib/python2.7/site-packages/sumatra/projects.py", line 233, in most_recent
      return self.get_record(self._most_recent)
    File "~/.pyenvs/sumatra/lib/python2.7/site-packages/sumatra/projects.py", line 208, in get_record
      return self.record_store.get(self.name, label)
    File "~/.pyenvs/sumatra/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 208, in get
      raise KeyError(label)
  KeyError: u'20131103-181500'
}}}

Work-around:
 * Specify the label explicitely `smt tag last_one 20131103-181000`

Sumatra version: 0.5.2
(Fresh from PyPI through pip, installed today)

Cheers!
        

 _Imported from Bitbucket issue [190](https://bitbucket.org/apdavison/sumatra/issue/190),  created by apdavison on 11-03-2013 at 19:08, last modified: 01-21-2014 at 14:39_

**Comment by apdavison** [comment]
Just checked, the same thing happens in Sumatra version 0.6.0dev.
        

_Trac comment by anonymous on 11-03-2013 at 19:36_

**Comment by apdavison** [comment]
Fixed in c5d365b451a3016553acdf7a0ad71bfa00b1eaac
        

_Trac comment by apdavison on 01-21-2014 at 14:39_
