### ISSUE TITLE
_find_new_data_files returns incorrect path when saving in subdirectories of datapath

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#178]
Error Log:
{{{
    Traceback (most recent call last):
      File "/usr/local/bin/smt", line 5, in <module>
        pkg_resources.run_script('Sumatra==0.5.2', 'smt')
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/EGG-INFO/scripts/smt", line 31, in <module>
        main(sys.argv[2:])
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/commands.py", line 328, in run
        launch_mode=launch_mode)
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/projects.py", line 173, in launch
        record.run(with_label=self.data_label)
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/records.py", line 158, in run
        self.output_data = self.datastore.find_new_data(self.timestamp)
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/datastore/filesystem.py", line 117, in find_new_data
        for path in self._find_new_data_files(timestamp)]
      File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/datastore/filesystem.py", line 27, in __init__
        raise IOError("File %s does not exist" % self.full_path)
    IOError: File data/raphs/flat/N-1000_v1.xml.gz does not exist
}}}

when data was saved to data/graphs/flat/N-1000_v1.xml.gz, where --datapath=data/

Proposed solution:

in datastore/filesystem.py line 108:
 relative_path = os.path.join(root[length_dataroot-1:],file)

        

 _Imported from Bitbucket issue [192](https://bitbucket.org/apdavison/sumatra/issue/192),  created by Felix11H on 11-27-2013 at 16:31, last modified: 01-21-2014 at 15:29_

**Comment by apdavison** [comment]
The problem arises because of the trailing slash in `datapath`.  This problem is already fixed in the development version, since we normalize the root path using `abspath()`. 
        

_Trac comment by apdavison on 01-21-2014 at 15:29_
