### ISSUE TITLE
TypeError for specific data set created with graph_tool

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#181]
Specific data set created with graph_tool (http://graph-tool.skewed.de/), attached to ticket (graph.xml.gz).

Supplying this file as input data to test.py immediately yields (even before version control check) a TypeError: expected string without null bytes.

Full trace stack:
{{{
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 5, in <module>
    pkg_resources.run_script('Sumatra==0.5.2', 'smt')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/EGG-INFO/scripts/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/commands.py", line 314, in run
    parameters, input_data, script_args = parse_arguments(args, project.input_datastore)
  File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/commands.py", line 93, in parse_arguments
    parameter_sets.append(build_parameters(arg))
  File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/parameters.py", line 445, in build_parameters
    parameters = SimpleParameterSet(filename)
  File "/usr/local/lib/python2.7/dist-packages/Sumatra-0.5.2-py2.7.egg/sumatra/parameters.py", line 158, in __init__
    self.values[name] = eval(value)
TypeError: expected string without null bytes
}}}

To reproduce just pass graph.xml.gz as argument to empty test script test.py:

smt run --executable=python --main=test.py data/graph.xml.gz

        

 _Imported from Bitbucket issue [195](https://bitbucket.org/apdavison/sumatra/issue/195),  created by Felix11H on 01-17-2014 at 08:54, last modified: 01-21-2014 at 15:10_

**Comment by apdavison** [comment]
should be fixed in 58e2c8181a1a23a37b69b0613c2492ff74fcfaf3
        

_Trac comment by apdavison on 01-21-2014 at 15:10_
