### ISSUE TITLE
smt run: Missing alarm functionality for subprocess with timeout on Windows

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#189]
I just tried the most recent Sumatra version (v.0.6.1dev) on Windows with a very simple script, which just prints "Hello World" and tried running it with ```smt run --executable=python --main=main.py```. This results in an error due to a missing signal in the ```signal``` module:
```
#!python
D:\sumatra0.6-test>smt run --executable=python --main=main.py
Using C:\Python27\python.exe
Traceback (most recent call last):
  File "C:\Python27\Scripts\smt", line 7, in <module>
    execfile(__file__)
  File "Y:\Python\sumatra\bin\smt", line 31, in <module>
    main(sys.argv[2:])
  File "y:\python\sumatra\sumatra\commands.py", line 349, in run
    executable = get_executable(path=executable_path)
  File "y:\python\sumatra\sumatra\programs.py", line 222, in get_executable
    program = registered_executables[prog_name](path)
  File "y:\python\sumatra\sumatra\programs.py", line 65, in __init__
    self.version = version or self._get_version()
  File "y:\python\sumatra\sumatra\programs.py", line 93, in _get_version
    shell=True, timeout=5)
  File "y:\python\sumatra\sumatra\core.py", line 58, in run
    signal.signal(signal.SIGALRM, alarm_handler)
AttributeError: 'module' object has no attribute 'SIGALRM'
```

Cause: the ```run``` function implements an approach published on [stackoverflow](http://stackoverflow.com/a/3326559), which is incompatible with Windows.

Possible workarounds:

* Backport of subprocess from Python 3, which supports timeout ([on PyPi](https://pypi.python.org/pypi/subprocess32/3.2.5))
* A thread-based solution [on stackoverflow](http://stackoverflow.com/questions/1191374/subprocess-with-timeout)
* [General discussion on stackoverflow](http://stackoverflow.com/questions/6947065/right-way-to-run-some-code-with-timeout-in-python)
        

 _Imported from Bitbucket issue [203](https://bitbucket.org/apdavison/sumatra/issue/203),  created by joschkazj on 04-22-2014 at 11:02, last modified: 04-30-2014 at 06:58_

**Comment by apdavison** [comment]
I had the same problem as Joschka and posted my thread-based solution to the Sumatra Google group [here](https://groups.google.com/forum/?hl=en-GB#!topic/sumatra-users/nXCHJf3Y69Y)

Repeating the relevant part of that post here:
... However, smt is broken in Windows, because the signal.signal and signal.alarm calls in core.py are Posix-only. Following the documentation link in your core.py run() function to its source http://stackoverflow.com/a/3326559, I read the discussion there about Windows-friendly equivalent solutions and replaced the run() function contents with the following (apologies if this gets mangled):

```
#!python


def run(args, cwd=None, shell=False, kill_tree=True, timeout=-1, env=None):
    from threading import Timer
    p = subprocess.Popen(args, shell=shell, cwd=cwd, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE, env=env)
    if timeout != -1:
        timer = Timer(timeout, p.kill)
        timer.start()
    stdout, stderr = p.communicate()
    if timeout != -1:
        timer.cancel()
    return p.returncode, stdout, stderr
```

According to the stackoverflow page, this *should* provide an OS-independent way to run the subprocess, although it doesn't implement your return -9 code if an exception occurs, but that is probably easy enough to do. I actually haven't tested this to see whether it works to kill a misbehaving subprocess - I just thought I'd suggest it here as a possible way to avoid the Posix-specific problem.

Note that in addition to ignoring the kill_tree parameter it also doesn't currently return the -9 return code if an exception occurs.
        

_Trac comment by gazzar on 04-30-2014 at 06:58_

**Comment by dacoex** [comment]
what is the status of this solution?
