### ISSUE TITLE
Enable multiple simulations

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#49]
I tried to run two simulations at the same time with sumatra (smt run --executable=python --main=main.py default.param). I got this error when I run the second simulation:

{{{
Traceback (most recent call last):
  File "/****/bin/smt", line 30, in <module>
    main(sys.argv[2:])
  File "/****/lib/python2.6/site-packages/sumatra/commands.py", line 195, in run
    launch_mode=launch_mode)
  File "/****/lib/python2.6/site-packages/sumatra/projects.py", line 117, in launch
    reason)
  File "/****/lib/python2.6/site-packages/sumatra/projects.py", line 108, in new_record
    record.register()
  File "/****/lib/python2.6/site-packages/sumatra/records.py", line 57, in register
    self.dependencies = dependency_finder.find_dependencies(self.main_file, self.executable, self.on_changed)
  File "/****/lib/python2.6/site-packages/sumatra/dependency_finder/__init__.py", line 30, in find_dependencies
    return python.find_dependencies(filename, on_changed)
  File "/****/lib/python2.6/site-packages/sumatra/dependency_finder/python.py", line 172, in find_dependencies
    packages = find_imported_packages(filename)
  File "/****/lib/python2.6/site-packages/sumatra/dependency_finder/python.py", line 162, in find_imported_packages
    os.remove("module_finder_output.txt")
OSError: [Errno 2] No such file or directory: 'module_finder_output.txt'
}}}
        

 _Imported from Bitbucket issue [46](https://bitbucket.org/apdavison/sumatra/issue/46),  created by apdavison on 08-03-2010 at 23:44, last modified: 03-14-2011 at 13:48_

**Comment by apdavison** [comment]
This has not been explicitly fixed, but the depdency finder machinery no longer uses the "module_finder_output.txt" file, and running two simulations at the same time seems to work (also see source:doc/faq.txt)
        

_Trac comment by apdavison on 03-14-2011 at 13:48_
