### ISSUE TITLE
ShelveRecordStore sometimes breaks with unicode project names

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#68]
Zunbeltz wrote:

{{{
I plan to write test for the bzr backend as it is for hg in
smt_test.py.
Before that I try to run
python smt_test.py
and I get the following error
============================================================
smt run --executable=python --main=main.py default.param
['smt', 'run', '--executable=python', '--main=main.py',
'default.param']
------------------------------------------------------------
Using /usr/bin/python
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
datastore.root =  /tmp/tmpcDVreb/Data
Sumatra is running the following command: /usr/bin/python  main.py
20110330-171041.param
Data key is [u'example2.dat']
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 5, in <module>
    pkg_resources.run_script('Sumatra==0.3.1.dev', 'smt')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467,
in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200,
in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/Sumatra-0.3.1.dev-
py2.6.egg/EGG-INFO/scripts/smt", line 33, in <module>
    main(sys.argv[2:])
  File "/usr/local/lib/python2.6/dist-packages/Sumatra-0.3.1.dev-
py2.6.egg/sumatra/commands.py", line 254, in run
    launch_mode=launch_mode)
  File "/usr/local/lib/python2.6/dist-packages/Sumatra-0.3.1.dev-
py2.6.egg/sumatra/projects.py", line 146, in launch
    self.add_record(record)
  File "/usr/local/lib/python2.6/dist-packages/Sumatra-0.3.1.dev-
py2.6.egg/sumatra/projects.py", line 171, in add_record
    self.record_store.save(self.name, record)
  File "/usr/local/lib/python2.6/dist-packages/Sumatra-0.3.1.dev-
py2.6.egg/sumatra/recordstore/shelve_store.py", line 35, in save
    if self.shelf.has_key(project_name):
  File "/usr/lib/python2.6/shelve.py", line 107, in has_key
    return key in self.dict
  File "/usr/lib/python2.6/_abcoll.py", line 342, in __contains__
    self[key]
  File "/usr/lib/python2.6/bsddb/__init__.py", line 267, in
__getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.6/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.6/bsddb/__init__.py", line 267, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found
Traceback (most recent call last):
  File "smt_test.py", line 146, in <module>
    main()
  File "smt_test.py", line 139, in main
    run_test(repos, options, working_dir, repos_dir)
  File "smt_test.py", line 127, in run_test
    getting_started(options)
  File "smt_test.py", line 82, in getting_started
    run("smt run --executable=python --main=main.py default.param")
  File "smt_test.py", line 38, in run
    subprocess.check_call(args)
  File "/usr/lib/python2.6/subprocess.py", line 488, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['smt', 'run', '--
executable=python', '--main=main.py', 'default.param']' returned non-
zero exit status 1

For me it seems that Data key is a unicode string and that cofusses
smt.
Could someone look at it?
}}}

I can't reproduce this on my machine, but the shelve module can use different database backends, so it seems as though the bsddb backend does not accept unicode keys, but others do. See http://bugs.python.org/issue1036490

        

 _Imported from Bitbucket issue [63](https://bitbucket.org/apdavison/sumatra/issue/63),  created by apdavison on 03-31-2011 at 13:06, last modified: 03-31-2011 at 14:56_

**Comment by apdavison** [comment]
Attempted fix in r231
        

_Trac comment by apdavison on 03-31-2011 at 13:18_
