### ISSUE TITLE
Sumatra fails when trying to parse JSON parameter file

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#70]
When smt is run with the following file in an argument
{{{
{
    "param1":false
}
}}}

an exception is raised:

{{{
Traceback (most recent call last):
  File "/Users/bartosz/.virtualenvs/sumatra_devel/bin/smt", line 7, in <module>
    execfile(__file__)
  File "/Users/bartosz/SVN/sumatra/src/smt", line 32, in <module>
    main(sys.argv[2:])
  File "/Users/bartosz/SVN/sumatra/sumatra/commands.py", line 238, in run
    parameters, input_data, script_args = parse_arguments(args)
  File "/Users/bartosz/SVN/sumatra/sumatra/commands.py", line 74, in parse_arguments
    parameter_sets.append(build_parameters(arg))
  File "/Users/bartosz/SVN/sumatra/sumatra/parameters.py", line 229, in build_parameters
    parameters = NTParameterSet("file://%s" % os.path.abspath(filename))
  File "/Users/bartosz/SVN/sumatra/sumatra/external/NeuroTools/parameters.py", line 234, in __init__
    initialiser = ParameterSet.read_from_str(pstr)
  File "/Users/bartosz/SVN/sumatra/sumatra/external/NeuroTools/parameters.py", line 193, in read_from_str
    D = eval(s, global_dict)
  File "<string>", line 2, in <module>
NameError: name 'false' is not defined
}}}

The problem is probably with NTParameterSet which tries to parse a json file and fails on {{{false}}} value, which is valid in json but not in Python.

        

 _Imported from Bitbucket issue [65](https://bitbucket.org/apdavison/sumatra/issue/65),  created by apdavison on 04-08-2011 at 13:51, last modified: 04-12-2011 at 13:54_

**Comment by apdavison** [comment]
Added support for using either "True" or "true" (similarly for fFalse) in NTParameterSet files - r233

        

_Trac comment by apdavison on 04-12-2011 at 13:54_
