### ISSUE TITLE
error when configured to store-diff

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#71]
I used sumatra since a while and always in the default configuration. When I want to run an
experiment it always complains to commit the latest changes. This can be useful but becomes annoying in an early experimental phase. 

My first comment is that it would be nice to improve the error message of this. Currently I see the whole Traceback which ends in:

{{{
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/projects.py", line 130, in new_record
    version, diff = self.update_code(working_copy, version)
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/projects.py", line 158, in update_code
    raise UncommittedModificationsError("Code has changed, please commit your changes")
sumatra.versioncontrol.UncommittedModificationsError: Code has changed, please commit your changes
}}}

Now I change the sumatra configuration to store the difference in case of modified files, but this produces an error. 
Here the output:

{{{
dedan@localhost ~/p/m/smt_test> smt configure -c store-diff
dedan@localhost ~/p/m/smt_test> smt run --main=smt_test.py test.param 
Using /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 5, in <module>
    pkg_resources.run_script('Sumatra==0.3.1.dev', 'smt')
  File "/Library/Python/2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 489, in run_script
    set's ``.entries`` (if it wasn't already present).
  File "/Library/Python/2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1207, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/EGG-INFO/scripts/smt", line 33, in <module>
    main(sys.argv[2:])
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/commands.py", line 258, in run
    launch_mode=launch_mode)
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/projects.py", line 144, in launch
    launch_mode, label, reason)
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/projects.py", line 130, in new_record
    version, diff = self.update_code(working_copy, version)
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/projects.py", line 159, in update_code
    working_copy.use_latest_version()
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/versioncontrol/_git.py", line 90, in use_latest_version
    self.use_version('master') # note that we are assuming all code is in the 'master' branch
  File "/Library/Python/2.6/site-packages/Sumatra-0.3.1.dev-py2.6.egg/sumatra/versioncontrol/_git.py", line 85, in use_version
    assert not self.has_changed()
AssertionError
}}}

        

 _Imported from Bitbucket issue [66](https://bitbucket.org/apdavison/sumatra/issue/66),  created by apdavison on 04-28-2011 at 09:02, last modified: 06-22-2011 at 21:23_

**Comment by apdavison** [comment]
fixed (hopefully) in r250
        

_Trac comment by apdavison on 06-22-2011 at 21:23_
