### ISSUE TITLE
smt run crashes when hostname is missing from /etc/hosts

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#72]
I have the following error only on one of the machines where I want to use sumatra and this is the only one running 2.7.

(gen)dedan@quesada ~/projects/smt_test $ smt run --main=smt_test.py test.param 
Python could not be found. Please supply the path to the /home/dedan/.virtualenvs/env2/bin/python executable.
Multiple versions found, using /home/dedan/.virtualenvs/gen/bin/python. If you wish to use a different version, please specify it explicitly
Traceback (most recent call last):
  File "/home/dedan/.virtualenvs/gen/bin/smt", line 33, in <module>
    main(sys.argv[2:])
  File "/home/dedan/.virtualenvs/gen/lib/python2.7/site-packages/sumatra/commands.py", line 254, in run
    launch_mode=launch_mode)
  File "/home/dedan/.virtualenvs/gen/lib/python2.7/site-packages/sumatra/projects.py", line 144, in launch
    launch_mode, label, reason)
  File "/home/dedan/.virtualenvs/gen/lib/python2.7/site-packages/sumatra/projects.py", line 135, in new_record
    record.register(working_copy)
  File "/home/dedan/.virtualenvs/gen/lib/python2.7/site-packages/sumatra/records.py", line 71, in register
    self.platforms = self.launch_mode.get_platform_information()
  File "/home/dedan/.virtualenvs/gen/lib/python2.7/site-packages/sumatra/launch.py", line 117, in get_platform_information
    ip_addr=socket.gethostbyname(network_name),
socket.gaierror: [Errno -2] Name or service not known

When I print the network_name from line 117 it gives me "quesada" which is the name of the host. 

        

 _Imported from Bitbucket issue [67](https://bitbucket.org/apdavison/sumatra/issue/67),  created by apdavison on 04-29-2011 at 15:20, last modified: 06-23-2011 at 20:18_

**Comment by apdavison** [comment]
need to handle the socket.gaierror exception. Could either wimp out and set ip_addr = 127.0.0.1 or try one of the more elaborate methods described in http://stackoverflow.com/questions/166506/finding-local-ip-addresses-in-python
        

_Trac comment by apdavison on 05-02-2011 at 12:30_

**Comment by apdavison** [comment]
Wimped out - see r255
        

_Trac comment by apdavison on 06-23-2011 at 20:18_
