### ISSUE TITLE
commit 236 : ed30381c98c5 broke the smt list command

### ISSUE THREAD

**Issue by apdavison** [fipymigrate/sumatra#82]
After updating to commit 236 : ed30381c98c5 I receive an error message for the smt list command

(gen)dedan@localhost:~/projects/mpi/runs-gensim: smt list
Traceback (most recent call last):
  File "/Users/dedan/.virtualenvs/gen/bin/smt", line 33, in <module>
    main(sys.argv[2:])
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/sumatra/commands.py", line 281, in list
    print project.format_records(tags=tags, mode=options.mode, format=options.format)
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/sumatra/projects.py", line 197, in format_records
    records = self.record_store.list(self.name, tags)
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/sumatra/recordstore/django_store/__init__.py", line 204, in list
    return [db_record.to_sumatra() for db_record in db_records]
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/models/query.py", line 107, in _result_iter
    self._fill_cache()
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/models/query.py", line 772, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/backends/util.py", line 34, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dedan/.virtualenvs/gen/lib/python2.6/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: no such column: django_store_record.stdout_stderr

        

 _Imported from Bitbucket issue [76](https://bitbucket.org/apdavison/sumatra/issue/76),  created by emuller on 05-20-2011 at 13:12, last modified: 05-26-2011 at 08:48_

**Comment by apdavison** [comment]
This happened because a new field was added which is not present in your existing record store. If you are comfortable with SQLite, you can just run the command "`ALTER TABLE "django_store_record" ADD COLUMN "stdout_stderr" text NOT NULL`".

Otherwise, you can upgrade your record store using smt. Normally, this should be simple, but since I forgot to include the `smt export` command in the 0.3.0 release (see ticket:74), there are a couple of extra steps.

First, *backup* your project directory, including the .smt sub-directory. Sumatra will do the backup for you anyway, but better safe than sorry.

Now revert your Sumatra installation to r235:
{{{
$ hg up -r235
}}}

Add the following to commands.py:
{{{
#!python
def export(argv):
    usage = "%prog export"
    description = dedent("""\
        Export a Sumatra project and its records to JSON. This is needed before running upgrade.""")
    parser = OptionParser(usage=usage,
                          description=description)
    (options, args) = parser.parse_args(argv)
    if len(args) != 0:
        parser.error('%prog export does not take any arguments.')
    # copy the project data
    import shutil
    shutil.copy(".smt/project", ".smt/project_export.json")
    # export the record data
    project = load_project()
    f = open(".smt/records_export.json", 'w')
    f.write(project.record_store.export(project.name))
    f.close()
}}}

and in your project directory run
{{{
$ smt export
}}}

Now pull the latest version of Sumatra:
{{{
$ hg revert src/commands.py
$ hg pull -u
}}}

and in your project directory run
{{{
$ smt upgrade
}}}

Now try 
{{{
$ smt list -l
}}}

and check that everything works, and that no information has been lost (I suggest you also use smtweb to check).


Next time, upgrading should be much simpler, just `smt export`, `hg pull -u`, `smt upgrade`.



        

_Trac comment by apdavison on 05-24-2011 at 09:50_
